services:
  web:
    container_name: chall
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./source/:/code

    ports:
      - 80:80
    environment:
      - TEAM_LINK=a60b49ed246/2
      - PYTHONUNBUFFERED=1
